use dbtlv;

CREATE TABLE IF NOT EXISTS postagem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title    VARCHAR(50) NULL,
	content   VARCHAR(250) NULL,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=INNODB;
